# Generated by Django 6.1 on 2026-08-22 23:07

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sculpture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('title_translation', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2026)])),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
                ('is_manually_reserved', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('insurance_rate_override', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('representative_sculpture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representing_themes', to='gallery.sculpture')),
            ],
        ),
        migrations.AddField(
            model_name='sculpture',
            name='themes',
            field=models.ManyToManyField(related_name='sculptures', to='gallery.theme'),
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_theme_name_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='sculpture',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='unique_sculpture_title_case_insensitive'),
        ),
    ]
