# Generated by Django 6.1 on 2026-08-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_sculpture_reserved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sculpture',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=10),
        ),
    ]
