# Generated by Django 6.1 on 2026-08-26 10:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_sculpture_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sculpture',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
