# Generated by Django 6.1 on 2026-08-31 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_sculpture_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sculpture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
