# Generated by Django 6.1 on 2026-09-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_sculpture_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='theme',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
