# Generated by Django 6.1 on 2026-09-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_rate', models.DecimalField(decimal_places=4, default=0.015, max_digits=5)),
            ],
        ),
    ]
