# Generated by Django 6.1 on 2026-09-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='owner_email',
            field=models.EmailField(default='vteodorof@rocketmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
