# Generated by Django 6.1 on 2026-09-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('RO', 'Romania'), ('UK', 'United Kingdom')], default='UK', max_length=2)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
