# Generated by Django 6.1 on 2026-09-07 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order'),
        ('gallery', '0005_sculpture_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=6)),
                ('insurance_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=7)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='checkout.order')),
                ('sculpture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.sculpture')),
            ],
        ),
    ]
